# Generated by Django 4.1.2 on 2022-10-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={},
        ),
    ]
